# Generated by Django 2.0.3 on 2018-03-30 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Panchayat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('panchayat', models.CharField(max_length=200)),
                ('dev_index', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=200)),
                ('taluka', models.CharField(max_length=200)),
                ('stdofliving', models.CharField(max_length=200)),
                ('health', models.CharField(max_length=200)),
                ('education', models.CharField(max_length=200)),
                ('hdi', models.CharField(max_length=200)),
            ],
        ),
    ]
