# Generated by Django 2.0.3 on 2018-03-31 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaa', '0003_rankedpanchayat'),
    ]

    operations = [
        migrations.CreateModel(
            name='villageDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('panchayat', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('xcor', models.CharField(max_length=200)),
                ('ycor', models.CharField(max_length=200)),
            ],
        ),
    ]
