# Generated by Django 2.0.3 on 2018-03-31 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaa', '0004_villagedetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='rankedpanchayat',
            name='rank',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
